# Generated by Django 6.0.6 on 2026-06-16 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuiaMuseo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=150, verbose_name='Nombre completo del guía')),
                ('anios_experiencia_guia', models.IntegerField(verbose_name='Años de experiencia')),
                ('idiomas_hablados', models.CharField(max_length=150, verbose_name='Idiomas hablados')),
            ],
        ),
        migrations.CreateModel(
            name='Museo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del museo')),
                ('ciudad', models.CharField(max_length=100)),
                ('anio_fundacion', models.IntegerField(verbose_name='Año de fundación')),
            ],
        ),
        migrations.CreateModel(
            name='Exhibicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_exhibicion', models.CharField(max_length=150, verbose_name='Título de la exhibición')),
                ('duracion_meses', models.IntegerField(verbose_name='Duración en meses')),
                ('costo_produccion', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo de producción')),
                ('tematica', models.CharField(max_length=100, verbose_name='Temática principal')),
                ('guia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lasexhibiciones', to='institucion.guiamuseo')),
            ],
        ),
        migrations.AddField(
            model_name='guiamuseo',
            name='museo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='losguias', to='institucion.museo'),
        ),
    ]
